services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    depends_on:
      - mosquitto
    volumes:
      - ./zigbee2mqtt/zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=America/Los_Angeles
    devices:
      - /dev/serial/by-id/usb-SONOFF_SONOFF_Dongle_Lite_MG21_0e8cea1ea4a3ef11b55f4ebd61ce3355-if00-port0:/dev/ttyUSB0
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: zigbee_db
      POSTGRES_USER: zigbee_user
      POSTGRES_PASSWORD: zigbee_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  worker:
    build: ./db_worker
    container_name: mqtt2db_worker
    restart: unless-stopped
    depends_on:
      - mosquitto
      - postgres
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      DB_HOST: postgres
      DB_NAME: zigbee_db
      DB_USER: zigbee_user
      DB_PASSWORD: zigbee_pass
      PYTHONUNBUFFERED: "1"      # ← add this line
  dashboard:
    build: ./dashboard
    container_name: dash_dashboard
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8050:8050"
    environment:
      DB_HOST: postgres
      DB_NAME: zigbee_db
      DB_USER: zigbee_user
      DB_PASSWORD: zigbee_pass
volumes:
  pgdata:
